### ISSUE TITLE
DBI::dbConnect eventually times out on laptop and hangs on server

### ISSUE THREAD

**Issue by famulare** [seattleflu/incidence-mapper#31]
I'm unable to connect to the database from either my laptop (Window10) or my workstation (Ubuntu). On the laptop, it hangs for about a minute before throwing an error:

line https://github.com/seattleflu/incidence-mapper/blob/fd2c5be6387bcfb04919fb34d8dec10451a6feaf/dbViewR/R/selectFromDB.R#L74

```
> rawData <- DBI::dbConnect(RPostgres::Postgres(), 
                     host=host_string, 
                     dbname = dbname_string, 
                     port=pgpass_file[[host_index]][2],  
                     user=pgpass_file[[host_index]][4], 
                     password=pgpass_file[[host_index]][5])

Error in connection_create(names(opts), as.vector(opts)) : 
  server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.
```

On the docker image on the server, it hangs (as in, I have to kill RStudio with htop) and never returns the error.  In both cases, the everything up to the dbConnect line works as far as I can tell.

**Comment by tsibley** [comment]
@devclinton Just a heads up that I'm simplifying the db connection logic a bit and will open a PR forose changes. I don't expect it to change the connection hangs, but wanted you to be aware.

**Comment by devclinton** [comment]
@famulare I am looking into this. Let me test this on a machine that I used to test psql on last week. Should have an update sometime this AM.

**Comment by devclinton** [comment]
It appears this is same issue we were encountering initially with the db connection. I am going to have to open a connection with ops because I am sporadically able to connect from my workstation. I am always able to establish a connection to the port using nc and telnet commands. However, I notice with the psql command that a connection is often never established. Insteald, the psql client just idles. I am thinking possibly some outgoing firewall or network rule is filtering our traffic

**Comment by devclinton** [comment]
https://helpdesk.idmod.org/browse/REQUEST-9250

**Comment by devclinton** [comment]
It appears we do have an outgoing firewall rule that got triggered for outgoing SQL. Hopefully our network admins will whitelist this our own end this will be resolved.

**Comment by devclinton** [comment]
This is now resolved
