### ISSUE TITLE
make it so we don't have to do git config --global by hand when container is rebuilt

### ISSUE THREAD

**Issue by famulare** [seattleflu/incidence-mapper#34]
After rebuilding the RStudio container, git config has to be done by hand

```
git config --global user.email "you@example.com"
git config --global user.name "Your Name"
```

**Comment by devclinton** [comment]
There is a fix for this now. It does require user intervention. I couldn't make a catch all config since it differs per user/operating system but I have added examples in the docker-compose.rstudio.yml file. 

To use the example, simply un-comment the appropriate line with the docker-compose.rstudio.yml line that references your local .gitconfig file. @famulare , you should use - **"${HOME}/.gitconfig:/home/rstudio/.gitconfig"** version. 

I also added some documentation on how to do the same for pgpass and pg_service.conf
